### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by pimskie** [vicompany/grunt-mustache-combine#2]
The name of the plugin can be a bit misleading since this plugin works for all kind of templates.
It doesn't matter if it are Mustache, EJS or Underscore templates for example.

**Comment by ba55ie** [comment]
Well, I haven't tested it with other templates, but I guess it should work. The problem is that some templates, unlike mustache, need to be [precompiled](http://handlebarsjs.com/precompilation.html).
